---
title: "Possible options for publication."
output: pdf_document
fig_caption: yes
header-includes:
  - \usepackage{xcolor}
  - \usepackage{caption}
  - \usepackage{float}
  - \usepackage{hyperref}
  - \hypersetup{    
        colorlinks=true,
        urlcolor=blue
        }
---

### Update from meeting 02/11
- Could write up as a response to a recent paper on household transmission paper.
- Individual based models
- Look at more data sets with age? 

# Quick note
During my chat with Deirdre at the end of summer, she suggested looking at opionion blogs *etc* of journals. She also suggested first picking a possible place to publish the piece and then tuning the writing to the particular style. \medskip \newline 
I tried looking at some options myself but felt relatively intimidated by the descriptions of the "standards/rigour" of the work accepted in most places. As you may have seen, our observations are reasonably qualitative (and not very novel) in nature. 

### Response to a recent COVID-19 paper
Writing a short opinion piece or communication in resposne to a recent paper on COVID-19 transmission in households vs non-households. 

### Mathematics Today
*\url{https://ima.org.uk/publications/mathematics-today/}* \smallskip \newline
Deidre said that the *Mathematics Today* publications are written in a more accessible and descrpitive spirit aimed at a wider scientifically-minded audience, possibly a good fit for the work we did. She shared \href{https://ima.org.uk/12771/predicting-extinction-of-filarial-worm-infections/}{this lovely article} that you have published recently. 

### The Conversation
*\url{https://theconversation.com/uk}* \smallskip \newline
They have a COVID-19 section where this would fit nicely. Not sure how to present our relatively simple findings as "news," but I suppose we could give them some twist. 

### BugBitten 
*\url{https://blogs.biomedcentral.com/bugbitten/}* \smallskip \newline
Another option, but the blog is oriented towards parasites and vectors; not sure if COVID-19 would be a good fit. 

### Microbiology Society Blog
*\url{https://microbiologysociety.org/blog.html?blog_category=events&publishMonth}* \smallskip \newline
Having had a brief look at the titles, this blog covers a range of topics, so ours might fit in... 

### Journal of Undergraduate Research
Deirdre mentioned this but hinted that we might want to shoot higher... 

### Some other suggestions from my naive research
I'm sliding into magazines (which might very well have better things to publish). \newline
\begin{itemize}
    \item New Scientist
        \begin{description}
        \item \emph{\url{https://www.newscientist.com/freelancers/}}
        \end{description}
    \item Science Daily
        \begin{description}
        \item \emph{\url{https://www.sciencedaily.com/contribute.htm}}
        \end{description}
    \end{itemize}



