```{r}
library("ggplot2")
library("plyr")
library("magrittr")
library("stringr")
library("patchwork")
library("animation")
```



```{r}
transmission_pairs_china = read.csv("C:\\Users\\sedar\\Documents\\Seda_Radoykova\\OneDrive - University College London\\Work\\Oxford_BDI_summer_2021\\Secondary distribution\\Data Catalogue\\seda\\freq_distr\\transmission_pairs_china.csv")
```


```{r}
transmission_pairs = dplyr::select(transmission_pairs_china, pair_id, infector_id, infector_age, infectee_id, infectee_age, is_household, infector_onset_date, infectee_onset_date)
head(transmission_pairs)


transmission_pairs$infector_age = as.integer(transmission_pairs$infector_age)
transmission_pairs$infectee_age = as.integer(transmission_pairs$infectee_age)
transmission_pairs$is_household = as.factor(transmission_pairs$is_household)
transmission_pairs$infector_onset_date = as.Date(transmission_pairs$infector_onset_date, 
                                                 format = "%m/%d/%y")
transmission_pairs$infectee_onset_date =  as.Date(transmission_pairs$infectee_onset_date, 
                                                 format = "%m/%d/%y")
```

```{r}
transmission_pairs$infector_age_bins5 <-
    cut(
        transmission_pairs$infector_age,
        breaks = seq(0, 95, 5),
        include.lowest = TRUE,
        right = FALSE
    )

transmission_pairs$infectee_age_bins5 <-
    cut(
        transmission_pairs$infectee_age,
        breaks = seq(0, 95, 5),
        include.lowest = TRUE,
        right = FALSE
    )

# table(transmission_pairs$infector_age_bins5)
# table(transmission_pairs$infectee_age_bins5)
```


```{r}
transpairs = transmission_pairs[complete.cases(transmission_pairs),]
cust_lab_names = levels(transpairs$infector_age_bins5)
cust_lab_names[seq(2,19,2)] = ""
```

# Subset pre and post-lockdown

- infector onset < (23 Jan - infectious period)
  - infectious period = 7 days 
- infectee onset < (23 Jan + incubation period)
  - incubation period = 3 days 



```{r}
infect_per = as.Date("2020-01-23") - 7
incub_per = as.Date("2020-01-23") + 3
  
transpairs$lockdown = rep(NA, nrow(transpairs)) # initialise lockdown 
transpairs$lockdown = ifelse((transpairs$infector_onset_date <= incub_per | transpairs$infectee_onset_date <= infect_per), "pre", "post")
```

```{r}
transpairs$lockdown = factor(transpairs$lockdown, 
                             levels = c("pre", "post"))
transpairs$is_household = factor(transpairs$is_household, 
                                 levels = c("yes", "no"))
```

```{r}
table(transpairs$is_household, transpairs$lockdown, useNA = "always")
```


## Before incub/infect period

        			Pre     Post	  Total
Household 		104	    224	    328
Non-household 110     222	    332
Total			    214	    446


## After incub/infect period

                Pre     Post  Total
Household       167     161   328
Non-household   180     152   332
Total           347     313


```{r}
household = transpairs[which(transpairs$is_household == "yes"),]
non_household = transpairs[which(transpairs$is_household != "yes"),]
table(transpairs$is_household)
table(transpairs$lockdown)
```




```{r}
######### LABELS 
house_labs = c(yes = "Household transmission", 
               no = "Non-household transmission")
lock_labs = c(pre = "Pre-lockdown", post = "Post-lockdown")

# facet grid
plt = ggplot(data = transpairs, aes(x = infector_age_bins5, 
                              y = infectee_age_bins5)) +
    geom_bin2d() +
    labs(x = "Infector age", y = "Infectee age") +#, title = .title) +
#    theme_minimal() +
    scale_fill_gradient2(
        low = "gray95",
        mid = "steelblue",
        midpoint = 5,
        limit = c(0, 10),
        breaks = c(0,2,4,6,8,10),
        space = "Lab", name = "Count") +
    scale_x_discrete(breaks = levels(household$infector_age_bins5),
                     labels = cust_lab_names) +
    theme(legend.title = element_blank(), legend.position = "right", 
          axis.text.x = element_text(angle = 15)) + 
    facet_grid(lockdown~is_household, 
               labeller = labeller(is_household = house_labs, 
                                   lockdown = lock_labs))
plt

ggsave(
    plt,
    file = paste0("household_lockdown_with_periods.png"),
    width = 20,
    height = 15,
    units = "cm"
)
```



```{r}
### check max coutns in every group to adjust scale colors 
table(
      household$infector_age_bins5,
      household$infectee_age_bins5,
      household$lockdown,
      useNA = "always") %>% max
table(
      non_household$infector_age_bins5,
      non_household$infectee_age_bins5,
      non_household$lockdown,
      useNA = "no") %>% max
```

### Try bootstrapping 

```{r}
plt_single = function(.data, .scale_range = c(0,10)){
    ggplot(data = .data, aes(x = infector_age_bins5, 
                              y = infectee_age_bins5)) +
    geom_bin2d() +
    labs(x = "Infector age", y = "Infectee age") +#, title = .title) +
#    theme_minimal() +
    scale_fill_gradient2(
        low = "gray95",
        mid = "steelblue",
        midpoint = .scale_range[2]/2,
        limit = .scale_range,
        breaks = seq(from = .scale_range[1], 
                     to = .scale_range[2], 
                     length.out = 6),
        space = "Lab", name = "Count") +
    scale_x_discrete(breaks = levels(household$infector_age_bins5),
                     labels = cust_lab_names) +
    theme(legend.title = element_blank(), legend.position = "right", 
          axis.text.x = element_text(angle = 15)) + 
    facet_grid(lockdown~is_household, 
               labeller = labeller(is_household = house_labs, 
                                   lockdown = lock_labs))
}
```


```{r}
## this sample seems to randomise all the data 
### add comma data[,c(cols)] OR data[c(cols)]??????
### this essentially samples from lockdown/no lockdown... 
## should we sample a date and then calculate lockdown/not?? 
        ## i.e. should we simulate some data or just draw samples? 
purrr::map(transpairs[,c("infector_onset_date", 
                              "infectee_onset_date", 
                              "infector_age_bins5", 
                              "infectee_age_bins5",
                              "is_household",
                              "lockdown")], 
       function(x) sample(x, 700, TRUE)) %>% as.data.frame %>% 
    plt_single(., c(0,13))
## lol sometimes it doesn't sample all the labels hahaha
```

```{r}
## this samples from the original groups
transpairs[sample(1:nrow(transpairs), 1000, T), ] %>% 
    plt_single(., c(0,19))
```

### Make gifs 

```{r}
# make plots and save in ggplot objects 

## this samples from the original groups
plts = list()
for (i in 1:50) {
    plts[[i]] = transpairs[sample(1:nrow(transpairs), 1000, T), ] %>% 
    plt_single(., c(0,22))
}

#plts
# saveGIF({
#     print(plts)
# }, ani.width = 2362*0.5, ani.height = 1771*0.5, interval = 1/2)
```

```{r}
## use this one for factors!!! 
plt_single = function(.data, .scale_range = c(0,10)){
  .data$lockdown = factor(.data$lockdown, 
                             levels = c("pre", "post"))
  .data$is_household = factor(.data$is_household, 
                                 levels = c("yes", "no"))
  house_labs = c(yes = "Household transmission", 
               no = "Non-household transmission")
  lock_labs = c(pre = "Pre-lockdown", post = "Post-lockdown")
  ggplot(data = .data, aes(x = infector_age_bins5, 
                              y = infectee_age_bins5)) +
    geom_bin2d() +
    labs(x = "Infector age", y = "Infectee age") +#, title = .title) +
#    theme_minimal() +
    scale_fill_gradient2(
        low = "gray95",
        mid = "steelblue",
        midpoint = .scale_range[2]/2,
        limit = .scale_range,
        breaks = seq(from = .scale_range[1], 
                     to = .scale_range[2], 
                     length.out = 6),
        space = "Lab", name = "Count") +
    scale_x_discrete(breaks = levels(household$infector_age_bins5),
                     labels = cust_lab_names) +
    theme(legend.title = element_blank(), legend.position = "right", 
          axis.text.x = element_text(angle = 15)) + 
    facet_grid(lockdown~is_household, 
               labeller = labeller(is_household = house_labs, 
                                   lockdown = lock_labs))
}
```


```{r}
## more randomised data 
plts_bs = list()
for (i in 1:50) {
plts_bs[[i]] = purrr::map(transpairs[,c("infector_onset_date", 
                              "infectee_onset_date", 
                              "infector_age_bins5", 
                              "infectee_age_bins5",
                              "is_household",
                              "lockdown")], 
       function(x) sample(x, 700, TRUE)) %>% as.data.frame %>% 
    plt_single(., c(0,13))
}

# saveGIF({
#     print(plts_bs)
# }, ani.width = 2362*0.5, ani.height = 1771*0.5, interval = 1/2)
```


```{r}
# save gifs
# save(plts, plts_bs, file = "data/boostratp_data_with_periods.RData")
load("data/boostratp_data_with_periods.RData")
```



